spring:
  datasource:
    url: jdbc:h2:mem:ecommerce
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        
  h2:
    console:
      enabled: true
      path: /h2-console

  task:
    execution:
      pool:
        core-size: 8
        max-size: 16
        queue-capacity: 500
    scheduling:
      pool:
        size: 4

logging:
  level:
    com.example.ecommerce: DEBUG
    org.springframework.transaction: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics